name = "memos-worker"
main = "src/index.js" # 或者 src/index.ts，根据项目实际结构而定
compatibility_date = "2024-01-01"

# 1. 绑定 D1 数据库
[[d1_databases]]
binding = "DB"              # 代码中调用的变量名，保持默认
database_name = "memos-db"      # 你在 Cloudflare 创建的 D1 数据库名
database_id = "17e09052-5e6a-4b11-b66f-df276ed545c7"    # 替换为你的真实 ID

# 2. 绑定 R2 存储桶（如果需要支持图片上传）
[[r2_buckets]]
binding = "BUCKET"                           # 代码中调用的变量名，保持默认
bucket_name = "memos-r2"                    # 你在 Cloudflare 创建的 R2 桶名
